### ISSUE TITLE
Pdf not displayed

### ISSUE THREAD

**Issue by abdallahkadour** [madmas/nativescript-pdf-view-angular-sample#11]
I cloned this project and started it, but no pdf is displayed.

**Comment by abdallahkadour** [comment]
In addition, the `main` entry of the project in package.json should be changed to `main.ts` since main.js does not exist.

**Comment by madmas** [comment]
Ho @abdallahkadour 
last thing I did to this demo was upgrade to NS 7 with the last release from the plugin.
Can you provide more details of you environment?
An on which OS is the PDF not shown?

**Comment by madmas** [comment]
@abdallahkadour please file an issue with the main repo is the error still persits
